# Generated by Django 6.0.5 on 2026-05-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0002_alter_partido_options_alter_partido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostico',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
