# Generated by Django 6.0.5 on 2026-05-31 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0003_pronostico_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoEliminatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.CharField(choices=[('R32', 'Round of 32'), ('R16', 'Round of 16'), ('QF', 'Cuartos de final'), ('SF', 'Semifinal'), ('3PL', 'Tercer y cuarto lugar'), ('FIN', 'Final')], max_length=3)),
                ('slot_local', models.CharField(max_length=50)),
                ('slot_visita', models.CharField(max_length=50)),
                ('local', models.CharField(blank=True, default='', max_length=50)),
                ('visita', models.CharField(blank=True, default='', max_length=50)),
                ('goles_l', models.IntegerField(blank=True, null=True)),
                ('goles_v', models.IntegerField(blank=True, null=True)),
                ('penales_l', models.IntegerField(blank=True, null=True)),
                ('penales_v', models.IntegerField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PronosticoEliminatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, default='', max_length=50)),
                ('visita', models.CharField(blank=True, default='', max_length=50)),
                ('goles_l', models.IntegerField(blank=True, null=True)),
                ('goles_v', models.IntegerField(blank=True, null=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prode.partidoeliminatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'partido')},
            },
        ),
    ]
