# Generated by Django 6.0.5 on 2026-06-02 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0005_mensaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default=0)),
                ('gl_retador', models.IntegerField(blank=True, null=True)),
                ('gv_retador', models.IntegerField(blank=True, null=True)),
                ('gl_retado', models.IntegerField(blank=True, null=True)),
                ('gv_retado', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prode.partido')),
                ('retado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_recibidos', to=settings.AUTH_USER_MODEL)),
                ('retador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
