# Generated by Django 6.0.5 on 2026-06-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0007_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
