# Generated by Django 6.0.5 on 2026-06-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0008_desafio_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='en_vivo',
            field=models.BooleanField(default=False),
        ),
    ]
