# Generated by Django 6.0.5 on 2026-06-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0010_votodesafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronosticoeliminatorio',
            name='ganador_penales',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
