# Generated by Django 6.0.5 on 2026-06-28 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0011_pronosticoeliminatorio_ganador_penales'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='partido_elim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prode.partidoeliminatorio'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prode.partido'),
        ),
    ]
