# Generated by Django 6.0.5 on 2026-06-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0012_desafio_partido_elim_alter_desafio_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidoeliminatorio',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
