# Generated by Django 6.0.5 on 2026-06-29 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0013_partidoeliminatorio_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionPodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primero', models.CharField(blank=True, default='', max_length=50)),
                ('segundo', models.CharField(blank=True, default='', max_length=50)),
                ('tercero', models.CharField(blank=True, default='', max_length=50)),
                ('cuarto', models.CharField(blank=True, default='', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
